import Foundation
import LAODomain

/// v0.8 node graph prompt builder — Phase 2 Step 4a (4행위 + 라우팅).
///
/// Conceptual flow: user message → director → one of {specifier, researcher, optionizer, gapDetector}
/// → single response. The director runs a focused JSON-schema classification call; the chosen step
/// runs a focused prose call. Any director failure (network / parse / unknown route) falls back to
/// specifier — preserves the "정정 안전망" intent from the vision so misroutes don't dead-end.
///
/// 5인 인물극 시각화 (color + icon + routing chip animation) lands in Step 4b.
///
/// `GraphNode` is explicitly module-qualified (`LAODomain.GraphNode`) because v0.7's
/// WorkGraphView.swift defines an internal type of the same name. The two namespaces stay
/// isolated until v0.7 is retired.
enum NodeGraphPromptBuilder {

    // MARK: - Director Routing

    /// Build the director routing prompt. The director classifies the user's latest message
    /// into one of the four step roles and returns JSON enforced by `NodeGraphJSONSchemas.directorRouting`.
    ///
    /// The director never produces user-facing prose — only routing metadata. The actual reply
    /// is generated by the chosen step on a second call.
    static func buildDirectorRoutingPrompt(
        project: Project,
        ideaTitle: String,
        focusedNode: LAODomain.GraphNode,
        branchContext: String?,
        chatHistory: [NodeMessage],
        userMessage: String
    ) -> String {
        var parts: [String] = []

        parts.append("""
        \(PromptFragments.designOfficeIdentityCompact)

        You are the **Director** — you do NOT answer the client directly. Your only job is to read \
        the client's latest message in the context of the focused mindmap node and decide which of \
        the four step agents should respond.

        ## The Four Step Agents
        - **specifier**: sharpens vague phrasing, makes concrete, refines wording. Pick when the client \
          asks "what exactly", "how would this look", "be more specific", or restates something that \
          needs precision.
        - **researcher**: surfaces similar examples, prior art, conventions, patterns. Pick when the \
          client asks "is there a precedent", "how do others do this", "any examples", or the node \
          would benefit from comparable references.
        - **optionizer**: presents 2–4 distinct options or alternative angles. Pick when the client \
          is undecided, asks "what are my choices", "any alternatives", or restates the node in a \
          way that suggests multiple plausible directions.
        - **gapDetector**: surfaces implicit assumptions, missing aspects, blind spots. Pick when \
          the client asks "what am I missing", "any blind spots", or the node is suspiciously thin \
          and you'd expect important details to be unstated.

        ## Decision Rule
        Pick the SINGLE step whose specialty best matches the client's intent. When the message is \
        ambiguous or just a vague "tell me more", default to **specifier** — it's the safest base case.

        Respond with ONLY valid JSON matching this shape:
        {"route": "specifier|researcher|optionizer|gapDetector", "reasoning": "<one short sentence>"}
        No commentary, no markdown fences.
        """)

        parts.append(projectContextBlock(project))
        parts.append(ideaSection(ideaTitle: ideaTitle, branchContext: branchContext))
        parts.append(focusedNodeSection(focusedNode))

        if let historyBlock = chatHistorySection(chatHistory) {
            parts.append(historyBlock)
        }

        parts.append("## Client's Latest Message\n\(userMessage)")

        return parts.joined(separator: "\n\n")
    }

    // MARK: - Step: Specifier

    /// Build the specifier prompt — the safest fallback. Sharpens vague phrasing and proposes
    /// a clearer formulation the client can react to.
    static func buildSpecifierPrompt(
        project: Project,
        ideaTitle: String,
        focusedNode: LAODomain.GraphNode,
        branchContext: String?,
        chatHistory: [NodeMessage],
        userProfile: UserProfile
    ) -> String {
        buildStepPrompt(
            roleHeader: """
            You are the **Specifier** — one of four step agents in the LAO Design Office. \
            Your job in this conversation: take the topic of a single mindmap node and make it concrete. \
            Sharpen vague phrasing, surface implicit assumptions, name the missing details, and propose \
            a clearer formulation the client can react to. You are NOT writing a final spec yet — you are \
            helping the client think the node through one focused step at a time.
            """,
            closingDirective: "End with a single concrete question OR a single concrete suggestion the client can accept/redirect.",
            project: project,
            ideaTitle: ideaTitle,
            focusedNode: focusedNode,
            branchContext: branchContext,
            chatHistory: chatHistory,
            userProfile: userProfile
        )
    }

    // MARK: - Step: Researcher

    /// Build the researcher prompt — pulls in comparable examples / patterns / conventions
    /// without inventing facts. Says "I don't know" if no concrete example comes to mind.
    static func buildResearcherPrompt(
        project: Project,
        ideaTitle: String,
        focusedNode: LAODomain.GraphNode,
        branchContext: String?,
        chatHistory: [NodeMessage],
        userProfile: UserProfile
    ) -> String {
        buildStepPrompt(
            roleHeader: """
            You are the **Researcher** — one of four step agents in the LAO Design Office. \
            Your job in this conversation: surface comparable examples, prior art, conventions, or \
            patterns relevant to the focused node. Name specific products / standards / well-known \
            approaches when you can; describe what they do and what makes the comparison apt. If you \
            don't actually know a concrete example, say so plainly rather than fabricating one.
            """,
            closingDirective: "End with how the referenced example informs the node (or honestly note when no comparable example came to mind).",
            project: project,
            ideaTitle: ideaTitle,
            focusedNode: focusedNode,
            branchContext: branchContext,
            chatHistory: chatHistory,
            userProfile: userProfile
        )
    }

    // MARK: - Step: Optionizer

    /// Build the optionizer prompt — presents 2–4 distinct angles the client can pick between.
    static func buildOptionizerPrompt(
        project: Project,
        ideaTitle: String,
        focusedNode: LAODomain.GraphNode,
        branchContext: String?,
        chatHistory: [NodeMessage],
        userProfile: UserProfile
    ) -> String {
        buildStepPrompt(
            roleHeader: """
            You are the **Optionizer** — one of four step agents in the LAO Design Office. \
            Your job in this conversation: lay out 2–4 distinct, materially different options for the \
            focused node. Each option should have a short label and a one-line consequence (what \
            changes if the client picks it). Options must actually be different — don't pad with \
            near-duplicates. If only one option is genuinely defensible, say so rather than inventing \
            alternatives.
            """,
            closingDirective: "End by asking which option the client wants to pursue, or naming the option you'd lean toward and why.",
            project: project,
            ideaTitle: ideaTitle,
            focusedNode: focusedNode,
            branchContext: branchContext,
            chatHistory: chatHistory,
            userProfile: userProfile
        )
    }

    // MARK: - Step: Gap Detector

    /// Build the gap-detector prompt — surfaces implicit assumptions and missing aspects the client
    /// is likely to skip past.
    static func buildGapDetectorPrompt(
        project: Project,
        ideaTitle: String,
        focusedNode: LAODomain.GraphNode,
        branchContext: String?,
        chatHistory: [NodeMessage],
        userProfile: UserProfile
    ) -> String {
        buildStepPrompt(
            roleHeader: """
            You are the **Gap Detector** — one of four step agents in the LAO Design Office. \
            Your job in this conversation: name what's missing or implicit around the focused node. \
            Think about edge cases, unstated dependencies, error states, permissions, empty states, \
            cross-axis consistency (Screen ↔ Data ↔ API ↔ Flow). Be specific about WHICH gap you're \
            naming — vague "consider X" doesn't help. Only flag gaps that genuinely matter for this node.
            """,
            closingDirective: "End by asking the client to decide on the highest-impact gap, or proposing how to close it.",
            project: project,
            ideaTitle: ideaTitle,
            focusedNode: focusedNode,
            branchContext: branchContext,
            chatHistory: chatHistory,
            userProfile: userProfile
        )
    }

    // MARK: - Shared Step Prompt Skeleton

    /// Common scaffold for all four step prompts. The role header and closing directive vary;
    /// everything else (response shape, project context, mindmap seed, focused node, history)
    /// is identical across steps so the agent always sees the same grounding structure.
    ///
    /// Step 5a: every step also gets a uniform "optional sub-node proposal" block so the
    /// mindmap can grow organically when a genuinely distinct sub-topic emerges. The block
    /// is opt-in per response — the prompt explicitly forbids padding.
    private static func buildStepPrompt(
        roleHeader: String,
        closingDirective: String,
        project: Project,
        ideaTitle: String,
        focusedNode: LAODomain.GraphNode,
        branchContext: String?,
        chatHistory: [NodeMessage],
        userProfile: UserProfile
    ) -> String {
        var parts: [String] = []

        parts.append("""
        \(PromptFragments.designOfficeIdentityCompact)\(PromptFragments.userContext(userProfile))

        \(roleHeader)

        ## Response Shape
        - One short prose turn. 2–5 sentences, or a compact bullet list if it genuinely helps.
        - No markdown headers in the prose; no JSON in the prose. Code fences are allowed ONLY for the optional proposal block described below.
        - \(closingDirective)
        - \(PromptFragments.respondInSameLanguage(as: "the most recent user message"))

        ## Optional Proposal Block
        After the prose, you MAY append ONE fenced block (never both). Pick the form that \
        matches the shape of what you're proposing:

        (a) A single distinct sub-topic that deserves its own focus area — drill-down:
        ```nodeProposal
        {"title": "<short noun phrase, ≤ 30 chars>", "body": "<one-line summary>"}
        ```

        (b) 2–4 distinct alternative angles on the focused node — parallel options that the \
        client might want to compare side-by-side:
        ```optionBranches
        [{"title": "<option A>", "body": "<one-line consequence>"}, {"title": "<option B>", "body": "<one-line consequence>"}]
        ```

        Skip both blocks when nothing concrete emerged — don't pad with low-value suggestions, \
        and don't propose a node that just restates the focused node itself. Use (b) only \
        when the alternatives are materially different from each other.
        """)

        parts.append(projectContextBlock(project))
        parts.append(ideaSection(ideaTitle: ideaTitle, branchContext: branchContext))
        parts.append(focusedNodeSection(focusedNode))

        if let historyBlock = chatHistorySection(chatHistory) {
            parts.append(historyBlock)
        }

        return parts.joined(separator: "\n\n")
    }

    // MARK: - Director Adoption Reasoning (Step 5c-1)

    /// Build the prompt that asks the director to narrate, in one short sentence, why one
    /// candidate branch is being adopted as the mainline over its siblings. The output goes
    /// into the parent node's conversation thread as a `.director`-authored message — this is
    /// the "추론 경로의 지도" trail the v0.8 vision relies on for explainable export.
    ///
    /// Failures must not block adoption: the caller persists the branchRole / status updates
    /// regardless of whether this LLM call succeeds.
    static func buildAdoptionReasoningPrompt(
        project: Project,
        ideaTitle: String,
        parentNode: LAODomain.GraphNode,
        adopted: LAODomain.GraphNode,
        siblings: [LAODomain.GraphNode],
        chatHistory: [NodeMessage]
    ) -> String {
        var parts: [String] = []

        parts.append("""
        \(PromptFragments.designOfficeIdentityCompact)

        You are the **Director**. The client just adopted one of several candidate branches \
        on a mindmap node as the mainline. Your job is to add a single short sentence to the \
        node's conversation explaining WHY this branch was chosen over the others — the kind \
        of brief comparative note that preserves the reasoning trail for later export.

        ## Response Shape
        - Exactly one sentence. 60–140 characters. No headers, no JSON, no code fences.
        - Reference the adopted option by title and compare against at least one sibling on a \
          specific axis (consistency, scope, risk, fit, etc.). Avoid hand-wavy phrases.
        - Start with a director-style opener that frames the decision ("큰 그림으로 보면…" / \
          "정리하면…" or the English equivalents).
        - \(PromptFragments.respondInSameLanguage(as: "the focused node title and conversation"))
        """)

        parts.append(projectContextBlock(project))
        parts.append(ideaSection(ideaTitle: ideaTitle, branchContext: branchContext(parentNode)))
        parts.append(focusedNodeSection(parentNode))

        var adoptedLines: [String] = [
            "## Adopted Option",
            "Title: \(adopted.title)",
        ]
        let trimmedAdoptedBody = adopted.body.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmedAdoptedBody.isEmpty {
            adoptedLines.append("Body: \(trimmedAdoptedBody)")
        }
        parts.append(adoptedLines.joined(separator: "\n"))

        if !siblings.isEmpty {
            var lines: [String] = ["## Other Candidates (folded)"]
            for sibling in siblings {
                let trimmedBody = sibling.body.trimmingCharacters(in: .whitespacesAndNewlines)
                if trimmedBody.isEmpty {
                    lines.append("- \(sibling.title)")
                } else {
                    lines.append("- \(sibling.title) — \(trimmedBody)")
                }
            }
            parts.append(lines.joined(separator: "\n"))
        }

        if let historyBlock = chatHistorySection(chatHistory) {
            parts.append(historyBlock)
        }

        return parts.joined(separator: "\n\n")
    }

    /// Light wrapper so the adoption prompt can reuse branchContext semantics without a node
    /// graph instance — the parent's own kind tells us the answer directly.
    private static func branchContext(_ node: LAODomain.GraphNode) -> String? {
        node.kind == .starter ? node.title : nil
    }

    // MARK: - Branch Merge (Step 5c-2)

    /// Build the prompt that asks the director to synthesize N candidate branches into a
    /// single new mainline node. The output JSON carries the new node's title/body plus a
    /// short reasoning line that the caller appends to the parent's conversation — preserving
    /// the merge rationale alongside the archived sources.
    ///
    /// JSON shape enforced by `NodeGraphJSONSchemas.merge`. Parse failures degrade to skipping
    /// the merge entirely (no half-merged state); see `MergeResponse`.
    static func buildMergePrompt(
        project: Project,
        ideaTitle: String,
        parentNode: LAODomain.GraphNode,
        candidates: [LAODomain.GraphNode],
        chatHistory: [NodeMessage]
    ) -> String {
        var parts: [String] = []

        parts.append("""
        \(PromptFragments.designOfficeIdentityCompact)

        You are the **Director**. The client wants to merge \(candidates.count) candidate \
        branches on a mindmap node into one new mainline branch. Your job is to synthesize \
        their best content into a single coherent option — pick a title and body that \
        captures the substance of all sources, not just one of them. Add a short reasoning \
        line that explains how you combined them.

        ## Response Format
        Respond with ONLY valid JSON matching this exact shape (no commentary, no markdown):
        {"title": "<short noun phrase, ≤ 30 chars>", "body": "<one-line summary of the merged option>", "reasoning": "<one sentence, 60–140 chars, naming each source and what survived>"}

        ## Synthesis Guidelines
        - The merged title should be a real combination, not the dominant source's title verbatim.
        - The body covers what the merged option actually IS — implementation-relevant, no fluff.
        - The reasoning sentence references each source by title and names what each contributed \
          (or why it was set aside). Avoid hand-wavy phrasing.
        - \(PromptFragments.respondInSameLanguage(as: "the parent node title and conversation"))
        """)

        parts.append(projectContextBlock(project))
        parts.append(ideaSection(ideaTitle: ideaTitle, branchContext: branchContext(parentNode)))
        parts.append(focusedNodeSection(parentNode))

        var sourcesLines: [String] = ["## Source Candidates"]
        for candidate in candidates {
            let trimmedBody = candidate.body.trimmingCharacters(in: .whitespacesAndNewlines)
            if trimmedBody.isEmpty {
                sourcesLines.append("- \(candidate.title)")
            } else {
                sourcesLines.append("- \(candidate.title) — \(trimmedBody)")
            }
        }
        parts.append(sourcesLines.joined(separator: "\n"))

        if let historyBlock = chatHistorySection(chatHistory) {
            parts.append(historyBlock)
        }

        return parts.joined(separator: "\n\n")
    }

    // MARK: - Proposal Parsing (Step 5a / 5b)

    /// Outcome of parsing the optional proposal block off an LLM response. At most one kind
    /// is returned — whichever fence appeared first in the response wins, so the agent's
    /// prompt instruction "never both" is enforced even if the model breaks it.
    enum ParsedProposal: Sendable {
        case none
        case child(NodeProposal)
        case branches([NodeProposal])
    }

    /// Split a raw LLM response into (prose, parsed proposal). Looks for `nodeProposal` and
    /// `optionBranches` fenced blocks; whichever opens first wins. Malformed or empty blocks
    /// degrade to `.none` with the prose preserved.
    static func extractAnyProposal(from response: String) -> (prose: String, kind: ParsedProposal) {
        let childMarker = "```nodeProposal"
        let branchesMarker = "```optionBranches"

        let childRange = response.range(of: childMarker)
        let branchesRange = response.range(of: branchesMarker)

        // Pick whichever block opens first. If neither is present, pass through.
        let chosen: (marker: String, range: Range<String.Index>, isBranches: Bool)?
        switch (childRange, branchesRange) {
        case let (.some(c), .some(b)):
            chosen = c.lowerBound < b.lowerBound
                ? (childMarker, c, false)
                : (branchesMarker, b, true)
        case let (.some(c), .none):
            chosen = (childMarker, c, false)
        case let (.none, .some(b)):
            chosen = (branchesMarker, b, true)
        case (.none, .none):
            return (response, .none)
        }
        guard let chosen else { return (response, .none) }

        guard let fenceEnd = response.range(of: "```", range: chosen.range.upperBound..<response.endIndex) else {
            let prose = String(response[..<chosen.range.lowerBound])
                .trimmingCharacters(in: .whitespacesAndNewlines)
            return (prose, .none)
        }
        let prose = String(response[..<chosen.range.lowerBound])
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let jsonBody = String(response[chosen.range.upperBound..<fenceEnd.lowerBound])
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !jsonBody.isEmpty, let data = jsonBody.data(using: .utf8) else {
            return (prose, .none)
        }

        if chosen.isBranches {
            guard let decoded = try? JSONDecoder().decode([NodeProposal].self, from: data) else {
                return (prose, .none)
            }
            // Drop entries with empty titles and require 2+ options to count as a branch set.
            // Lone option degrades silently to no-proposal rather than a single child.
            let kept = decoded.filter { !$0.title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
            guard kept.count >= 2 else { return (prose, .none) }
            return (prose, .branches(kept))
        } else {
            guard let decoded = try? JSONDecoder().decode(NodeProposal.self, from: data),
                  !decoded.title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
                return (prose, .none)
            }
            return (prose, .child(decoded))
        }
    }

    // MARK: - Sections

    private static func projectContextBlock(_ project: Project) -> String {
        var lines: [String] = ["## Project Context", "Project: \(project.name)"]
        if !project.description.isEmpty {
            lines.append("Description: \(project.description)")
        }
        if !project.rootPath.isEmpty {
            lines.append("Root Path: \(project.rootPath)")
        }
        return lines.joined(separator: "\n")
    }

    private static func ideaSection(ideaTitle: String, branchContext: String?) -> String {
        var lines: [String] = ["## Mindmap Seed", "Idea: \(ideaTitle)"]
        if let branchContext, !branchContext.isEmpty {
            lines.append("Branch: \(branchContext)")
        }
        return lines.joined(separator: "\n")
    }

    private static func focusedNodeSection(_ focusedNode: LAODomain.GraphNode) -> String {
        var lines: [String] = [
            "## Focused Node",
            "Title: \(focusedNode.title)",
            "Kind: \(focusedNode.kind.rawValue)",
            "Status: \(focusedNode.status.rawValue)",
        ]
        let trimmedBody = focusedNode.body.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmedBody.isEmpty {
            lines.append("Body:\n\(trimmedBody)")
        }
        return lines.joined(separator: "\n")
    }

    /// Renders the full per-node chat history as a labelled transcript.
    /// Returns nil when the history is empty.
    private static func chatHistorySection(_ messages: [NodeMessage]) -> String? {
        guard !messages.isEmpty else { return nil }
        var lines: [String] = ["## Conversation So Far"]
        for message in messages {
            lines.append("**\(label(for: message.author))**: \(message.content)")
        }
        return lines.joined(separator: "\n")
    }

    private static func label(for author: NodeMessageAuthor) -> String {
        switch author {
        case .user: return "Client"
        case .director: return "Director"
        case .specifier: return "Specifier"
        case .researcher: return "Researcher"
        case .optionizer: return "Optionizer"
        case .gapDetector: return "Gap Detector"
        }
    }
}

// MARK: - JSON Schemas

/// JSON schemas for node graph LLM responses. Mirrors `DesignJSONSchemas` / `IdeaJSONSchemas`
/// — strict mode (additionalProperties:false, every property in required), one-line per schema
/// to match the v0.7 convention. The schema is also the authoritative list of route enum values.
enum NodeGraphJSONSchemas {

    /// Director routing classification result.
    /// `route` enum mirrors `DirectorRoute` raw values — keep them in sync.
    static let directorRouting = """
    {"type":"object","properties":{"route":{"type":"string","enum":["specifier","researcher","optionizer","gapDetector"]},"reasoning":{"type":"string"}},"required":["route","reasoning"],"additionalProperties":false}
    """

    /// Merge synthesis result — new node title/body plus a reasoning sentence narrating how
    /// the sources were combined. Decoded into `MergeResponse`.
    static let merge = """
    {"type":"object","properties":{"title":{"type":"string"},"body":{"type":"string"},"reasoning":{"type":"string"}},"required":["title","body","reasoning"],"additionalProperties":false}
    """
}

// MARK: - Director Route

/// Outcome of the director's intent classification. Maps 1:1 to the four step agents and
/// to a subset of `NodeMessageAuthor` (excluding `.user` and `.director`).
enum DirectorRoute: String, Codable, Sendable {
    case specifier
    case researcher
    case optionizer
    case gapDetector

    /// The author tag to stamp on the resulting NodeMessage so the UI knows who spoke.
    var messageAuthor: NodeMessageAuthor {
        switch self {
        case .specifier: return .specifier
        case .researcher: return .researcher
        case .optionizer: return .optionizer
        case .gapDetector: return .gapDetector
        }
    }
}

/// Decoded shape of the director's JSON response. Decode failures fall back to `.specifier`
/// at the ViewModel layer.
struct DirectorRoutingResponse: Codable, Sendable {
    let route: DirectorRoute
    let reasoning: String
}

// MARK: - Sub-Node Proposal (Step 5a)

/// A transient AI suggestion to spawn a new child of the focused node. Decoded out of the
/// optional ```nodeProposal``` block in a step agent's response. Lives in ViewModel state until
/// the user approves (→ persisted `GraphNode` + `parentChild` edge) or dismisses (→ discarded).
/// Not stored on `NodeMessage` itself — proposals are session-only by design in Step 5a so the
/// conversation thread stays focused on prose.
struct NodeProposal: Codable, Hashable, Sendable {
    let title: String
    let body: String
}

// MARK: - Merge Response (Step 5c-2)

/// Decoded shape of the merge LLM response. Strict JSON enforced by
/// `NodeGraphJSONSchemas.merge`. Decode failures abort the merge entirely so we never end up
/// with a half-synthesized node.
struct MergeResponse: Codable, Sendable {
    let title: String
    let body: String
    let reasoning: String
}
